### PR TITLE
meme keyword

### PR DESCRIPTION
**Pull request by somxr**
Added definitions for my keyword, meme

### CODE REVIEW

**Review by vigliensoni — CHANGES_REQUESTED** [review]
We are using Chicago author-date. Here is your third, as an example:

Shifman, Limor. 2013. “Memes in a Digital World: Reconciling with a Conceptual Troublemaker.” *Journal of Computer-Mediated Communication* 18, no. 3: 362–77. https://doi.org/10.1111/jcc4.12013.

**Comment by somxr** [comment]
thanks for the example I didn't realize there was multiple chicago styles. Hope it's good to go now

**Comment by vigliensoni** [comment]
Merged but you missed the italics from the version I sent you.

**Comment by vigliensoni** [comment]
Also, keep an eye on the header: there's a missing space between the hash and the keyword. Check what is happening: https://github.com/concordia-dcart/CART210-glossary/blob/main/glossary.md#internet

It should be

```
## Meme
```

**Pull request merged**
